spring.application.name=BurguerKing
spring.datasource.url=jdbc:mysql://localhost:3306/spring-turmaA
spring.datasource.username=root
spring.datasource.password=root
spring.jpa.hibernate.ddl-auto=update